name: Scan with Aikido
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
      
permissions: read-all

jobs:
  trivy:
    name: Aikido Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Detect new vulnerabilities
        uses: AikidoSec/github-actions-workflow@main
        with:
            secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
            fail-on-timeout: true
            fail-on-dependency-scan: true
            fail-on-sast-scan: true
            fail-on-iac-scan: true
            minimum-severity: 'CRITICAL'
