name: cost-allocation-tags

on:
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  packages: read
  pull-requests: read
  repository-projects: read

jobs:
   cost-allocation-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zeus-health/ci-worker
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: check if REQ_WORKFLOW_PAT exists
        run: if [ `echo ${{secrets.REQ_WORKFLOW_PAT}} | wc -c` -lt 2 ]; then echo the secret \"REQ_WORKFLOW_PAT\" is not available; echo please contact InfraSec team to enable at Org level for this repo; exit 1; fi
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REQ_WORKFLOW_PAT }}
          repository: zeus-health/required-workflows
          ref: feature/INFR-648-deafult_tags
          path: required-workflows
          set-safe-directory: 'cost_allocation_tags'
      - name: Check for AWS cost allocation tags
        shell: bash
        run: | # exclude the required-workflows directory, it's not the repo being inspected
          find ~+ -type f -not -path '*/.*' -not -path "*/required-workflows/*" -name '*.tf' -print > required-workflows/cost_allocation_tags/TF_FILES.tmp
      - name: Check for AWS cost allocation tags
        shell: bash
        working-directory: required-workflows/cost_allocation_tags
        run: |
          ./main.sh pwd
